# Generated by Django 5.0.6 on 2024-05-11 02:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cep", models.CharField(max_length=8, verbose_name="CEP")),
                ("street", models.CharField(max_length=100, verbose_name="Rua")),
                ("number", models.IntegerField(verbose_name="Número")),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "neighborhood",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
            },
        ),
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "sheltered_number",
                    models.IntegerField(verbose_name="Número de abrigados"),
                ),
                (
                    "amount_lunchbox",
                    models.IntegerField(verbose_name="Quantidade de marmitas"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="voluntary.address",
                        verbose_name="Endereço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abrigo",
                "verbose_name_plural": "Abrigos",
            },
        ),
        migrations.CreateModel(
            name="Voluntary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("cpf", models.CharField(max_length=11, verbose_name="CPF")),
                (
                    "team_type",
                    models.CharField(max_length=100, verbose_name="Tipo de equipe"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="voluntary.address",
                        verbose_name="Endereço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voluntário",
                "verbose_name_plural": "Voluntários",
            },
        ),
        migrations.CreateModel(
            name="VoluntaryAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="voluntary.shelter",
                        verbose_name="Abrigo",
                    ),
                ),
                (
                    "voluntary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="voluntary.voluntary",
                        verbose_name="Voluntário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alocação de voluntário",
                "verbose_name_plural": "Alocações de voluntários",
            },
        ),
    ]
